name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v2

      - name: Check for sudo
        shell: bash
        run: |
          if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
          echo "SUDO=$SUDO" >> $GITHUB_ENV

      - name: Install dependencies
        shell: bash
        run: if [ -f install-deps ]; then $SUDO ./install-deps; fi

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_SANITIZER='Address;Undefined'

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
